import { collection, doc, getDocs, writeBatch } from "firebase/firestore";
import { db, firebaseReady } from "./firebase";
import type { Career, College } from "./types";

export const careerSeeds: Career[] = [
  { id: "software-engineer", title: "Software Engineer", category: "STEM", salaryRange: "$95k-$170k", growthOutlook: "High", educationLevel: "Bachelor's in Computer Science or related field", skills: ["Programming", "Systems thinking", "Debugging", "Collaboration"], relatedMajors: ["Computer Science", "Software Engineering", "Data Science"], description: "Designs, builds, and improves software products used by people and organizations." },
  { id: "ux-designer", title: "UX Designer", category: "Arts", salaryRange: "$72k-$135k", growthOutlook: "High", educationLevel: "Bachelor's in Design, HCI, or Psychology", skills: ["Research", "Prototyping", "Visual design", "Empathy"], relatedMajors: ["Human-Computer Interaction", "Graphic Design", "Psychology"], description: "Creates intuitive digital experiences through research, prototyping, and usability testing." },
  { id: "data-scientist", title: "Data Scientist", category: "STEM", salaryRange: "$100k-$180k", growthOutlook: "High", educationLevel: "Bachelor's or Master's in Statistics, CS, or Math", skills: ["Statistics", "Python", "Machine learning", "Storytelling"], relatedMajors: ["Data Science", "Statistics", "Mathematics"], description: "Turns complex data into predictions, insights, and decisions." },
  { id: "mechanical-engineer", title: "Mechanical Engineer", category: "STEM", salaryRange: "$78k-$130k", growthOutlook: "Medium", educationLevel: "Bachelor's in Mechanical Engineering", skills: ["CAD", "Physics", "Testing", "Manufacturing"], relatedMajors: ["Mechanical Engineering", "Physics", "Robotics"], description: "Develops machines, products, and mechanical systems from concept through production." },
  { id: "nurse-practitioner", title: "Nurse Practitioner", category: "Healthcare", salaryRange: "$105k-$160k", growthOutlook: "High", educationLevel: "Master's in Nursing", skills: ["Patient care", "Diagnosis", "Communication", "Clinical judgment"], relatedMajors: ["Nursing", "Biology", "Public Health"], description: "Provides advanced patient care, diagnoses conditions, and manages treatment plans." },
  { id: "physical-therapist", title: "Physical Therapist", category: "Healthcare", salaryRange: "$82k-$125k", growthOutlook: "High", educationLevel: "Doctor of Physical Therapy", skills: ["Anatomy", "Coaching", "Rehabilitation", "Assessment"], relatedMajors: ["Kinesiology", "Biology", "Health Sciences"], description: "Helps patients recover movement, strength, and quality of life after injuries or illness." },
  { id: "marketing-manager", title: "Marketing Manager", category: "Business", salaryRange: "$88k-$160k", growthOutlook: "Medium", educationLevel: "Bachelor's in Marketing or Business", skills: ["Strategy", "Analytics", "Branding", "Campaigns"], relatedMajors: ["Marketing", "Business Administration", "Communications"], description: "Plans campaigns and market strategies that help organizations grow." },
  { id: "financial-analyst", title: "Financial Analyst", category: "Business", salaryRange: "$76k-$130k", growthOutlook: "Medium", educationLevel: "Bachelor's in Finance, Economics, or Accounting", skills: ["Modeling", "Excel", "Risk analysis", "Research"], relatedMajors: ["Finance", "Economics", "Accounting"], description: "Evaluates investments, budgets, and business performance to guide financial choices." },
  { id: "teacher", title: "Teacher", category: "Education", salaryRange: "$48k-$85k", growthOutlook: "Medium", educationLevel: "Bachelor's in Education plus certification", skills: ["Instruction", "Planning", "Mentoring", "Assessment"], relatedMajors: ["Education", "English", "Mathematics"], description: "Guides students through learning, growth, and classroom experiences." },
  { id: "lawyer", title: "Lawyer", category: "Law", salaryRange: "$85k-$210k", growthOutlook: "Medium", educationLevel: "Bachelor's degree plus JD", skills: ["Argumentation", "Research", "Writing", "Negotiation"], relatedMajors: ["Political Science", "Pre-Law", "History"], description: "Advises clients, researches legal issues, and represents cases or agreements." },
  { id: "graphic-designer", title: "Graphic Designer", category: "Arts", salaryRange: "$52k-$95k", growthOutlook: "Low", educationLevel: "Bachelor's in Graphic Design or portfolio equivalent", skills: ["Typography", "Brand systems", "Illustration", "Layout"], relatedMajors: ["Graphic Design", "Visual Arts", "Marketing"], description: "Creates visual assets for brands, products, publications, and campaigns." },
  { id: "civil-engineer", title: "Civil Engineer", category: "STEM", salaryRange: "$76k-$124k", growthOutlook: "Medium", educationLevel: "Bachelor's in Civil Engineering", skills: ["Structures", "Planning", "Safety", "Project management"], relatedMajors: ["Civil Engineering", "Environmental Engineering", "Urban Planning"], description: "Designs and maintains infrastructure such as roads, bridges, buildings, and water systems." },
];

export const collegeSeeds: College[] = [
  { id: "stanford", name: "Stanford University", city: "Stanford", state: "CA", type: "Private", tuition: 62484, acceptanceRate: 4, enrollment: 17680, majors: ["Computer Science", "Mechanical Engineering", "Human-Computer Interaction", "Economics"], description: "A research university known for engineering, entrepreneurship, and interdisciplinary programs." },
  { id: "ucla", name: "UCLA", city: "Los Angeles", state: "CA", type: "Public", tuition: 14478, acceptanceRate: 9, enrollment: 47518, majors: ["Biology", "Psychology", "Computer Science", "Political Science", "Visual Arts"], description: "A large public university with strong academics, research, arts, and health sciences." },
  { id: "uc-berkeley", name: "UC Berkeley", city: "Berkeley", state: "CA", type: "Public", tuition: 15891, acceptanceRate: 12, enrollment: 45745, majors: ["Computer Science", "Data Science", "Civil Engineering", "Economics"], description: "A flagship public research university with leading STEM and social science programs." },
  { id: "caltech", name: "Caltech", city: "Pasadena", state: "CA", type: "Private", tuition: 63255, acceptanceRate: 3, enrollment: 2463, majors: ["Physics", "Mechanical Engineering", "Mathematics", "Computer Science"], description: "A small science and engineering institute with deep research opportunities." },
  { id: "usc", name: "University of Southern California", city: "Los Angeles", state: "CA", type: "Private", tuition: 68237, acceptanceRate: 10, enrollment: 49318, majors: ["Business Administration", "Communications", "Computer Science", "Marketing"], description: "A private university with strong professional schools and a broad alumni network." },
  { id: "nyu", name: "NYU", city: "New York", state: "NY", type: "Private", tuition: 60438, acceptanceRate: 12, enrollment: 59659, majors: ["Finance", "Graphic Design", "Marketing", "Psychology"], description: "An urban private university with global campuses and strengths in business, arts, and social science." },
  { id: "columbia", name: "Columbia University", city: "New York", state: "NY", type: "Private", tuition: 68556, acceptanceRate: 4, enrollment: 36880, majors: ["Political Science", "Economics", "Computer Science", "History"], description: "An Ivy League university in New York City with a rigorous core curriculum." },
  { id: "cornell", name: "Cornell University", city: "Ithaca", state: "NY", type: "Private", tuition: 66014, acceptanceRate: 7, enrollment: 26284, majors: ["Mechanical Engineering", "Hotel Administration", "Biology", "Computer Science"], description: "A large Ivy League university with broad programs from engineering to agriculture." },
  { id: "suny-buffalo", name: "University at Buffalo", city: "Buffalo", state: "NY", type: "Public", tuition: 10782, acceptanceRate: 68, enrollment: 32500, majors: ["Nursing", "Civil Engineering", "Business Administration", "Education"], description: "A SUNY research university with strong value and extensive academic options." },
  { id: "syracuse", name: "Syracuse University", city: "Syracuse", state: "NY", type: "Private", tuition: 63880, acceptanceRate: 52, enrollment: 22000, majors: ["Communications", "Graphic Design", "Marketing", "Political Science"], description: "A private university known for communications, public affairs, business, and design." },
  { id: "ut-austin", name: "UT Austin", city: "Austin", state: "TX", type: "Public", tuition: 11698, acceptanceRate: 29, enrollment: 52000, majors: ["Computer Science", "Finance", "Mechanical Engineering", "Marketing"], description: "Texas flagship university with nationally recognized business, engineering, and liberal arts." },
  { id: "rice", name: "Rice University", city: "Houston", state: "TX", type: "Private", tuition: 58128, acceptanceRate: 8, enrollment: 8565, majors: ["Statistics", "Bioengineering", "Economics", "Architecture"], description: "A selective private university with a residential college system and strong STEM programs." },
  { id: "texas-am", name: "Texas A&M University", city: "College Station", state: "TX", type: "Public", tuition: 13239, acceptanceRate: 63, enrollment: 74500, majors: ["Mechanical Engineering", "Civil Engineering", "Nursing", "Business Administration"], description: "A large public research university with notable engineering and professional programs." },
  { id: "baylor", name: "Baylor University", city: "Waco", state: "TX", type: "Private", tuition: 54420, acceptanceRate: 46, enrollment: 20500, majors: ["Nursing", "Biology", "Accounting", "Education"], description: "A private Christian university with strong health, business, and education pathways." },
  { id: "mit", name: "MIT", city: "Cambridge", state: "MA", type: "Private", tuition: 60156, acceptanceRate: 4, enrollment: 11934, majors: ["Computer Science", "Data Science", "Mechanical Engineering", "Physics"], description: "A world-leading institute for technology, engineering, science, and innovation." },
  { id: "boston-university", name: "Boston University", city: "Boston", state: "MA", type: "Private", tuition: 66670, acceptanceRate: 14, enrollment: 37000, majors: ["Communications", "Physical Therapy", "Finance", "Public Health"], description: "A major urban research university with wide-ranging professional and liberal arts programs." },
  { id: "harvard", name: "Harvard University", city: "Cambridge", state: "MA", type: "Private", tuition: 59076, acceptanceRate: 3, enrollment: 25000, majors: ["Economics", "Political Science", "History", "Biology"], description: "A historic private university with broad strengths across disciplines." },
  { id: "northeastern", name: "Northeastern University", city: "Boston", state: "MA", type: "Private", tuition: 63800, acceptanceRate: 7, enrollment: 31000, majors: ["Computer Science", "Business Administration", "Health Sciences", "Data Science"], description: "Known for co-op education, career preparation, and experiential learning." },
  { id: "uiuc", name: "University of Illinois Urbana-Champaign", city: "Champaign", state: "IL", type: "Public", tuition: 17712, acceptanceRate: 45, enrollment: 56000, majors: ["Computer Science", "Civil Engineering", "Accounting", "Education"], description: "A Big Ten public university with top-ranked engineering, business, and computer science." },
  { id: "northwestern", name: "Northwestern University", city: "Evanston", state: "IL", type: "Private", tuition: 65997, acceptanceRate: 7, enrollment: 23000, majors: ["Journalism", "Economics", "Theater", "Political Science"], description: "A selective private university with strengths in journalism, arts, research, and business." },
  { id: "ohio-state", name: "Ohio State University", city: "Columbus", state: "OH", type: "Public", tuition: 13000, acceptanceRate: 53, enrollment: 66000, majors: ["Education", "Nursing", "Finance", "Mechanical Engineering"], description: "A large public research university with extensive majors and school spirit." },
  { id: "uw", name: "University of Washington", city: "Seattle", state: "WA", type: "Public", tuition: 12973, acceptanceRate: 48, enrollment: 60000, majors: ["Computer Science", "Public Health", "Data Science", "Biology"], description: "A public research university with strong tech, health, and science connections." },
];

export async function seedDataIfNeeded() {
  if (!firebaseReady) return;
  const [careerSnap, collegeSnap] = await Promise.all([getDocs(collection(db, "careers")), getDocs(collection(db, "colleges"))]);
  const batch = writeBatch(db);
  if (careerSnap.empty) {
    careerSeeds.forEach((career) => batch.set(doc(db, "careers", career.id), career));
  }
  if (collegeSnap.empty) {
    collegeSeeds.forEach((college) => batch.set(doc(db, "colleges", college.id), college));
  }
  if (careerSnap.empty || collegeSnap.empty) await batch.commit();
}
