import { collection, doc, getDocs, writeBatch } from "firebase/firestore";
import { db, firebaseReady } from "./firebase";
import type { Career, College } from "./types";

export const careerSeeds: Career[] = [
  { id: "software-engineer", title: "Software Engineer", category: "STEM", salaryRange: "₹8L - ₹25L", growthOutlook: "High", educationLevel: "Bachelor's in Computer Science or related field", skills: ["Programming", "Systems thinking", "Debugging", "Collaboration"], relatedMajors: ["Computer Science", "Software Engineering", "Data Science"], description: "Designs, builds, and improves software products used by people and organizations." },
  { id: "ux-designer", title: "UX Designer", category: "Arts", salaryRange: "₹6L - ₹18L", growthOutlook: "High", educationLevel: "Bachelor's in Design, HCI, or Psychology", skills: ["Research", "Prototyping", "Visual design", "Empathy"], relatedMajors: ["Human-Computer Interaction", "Graphic Design", "Psychology"], description: "Creates intuitive digital experiences through research, prototyping, and usability testing." },
  { id: "data-scientist", title: "Data Scientist", category: "STEM", salaryRange: "₹10L - ₹28L", growthOutlook: "High", educationLevel: "Bachelor's or Master's in Statistics, CS, or Math", skills: ["Statistics", "Python", "Machine learning", "Storytelling"], relatedMajors: ["Data Science", "Statistics", "Mathematics"], description: "Turns complex data into predictions, insights, and decisions." },
  { id: "mechanical-engineer", title: "Mechanical Engineer", category: "STEM", salaryRange: "₹5L - ₹15L", growthOutlook: "Medium", educationLevel: "Bachelor's in Mechanical Engineering", skills: ["CAD", "Physics", "Testing", "Manufacturing"], relatedMajors: ["Mechanical Engineering", "Physics", "Robotics"], description: "Develops machines, products, and mechanical systems from concept through production." },
  { id: "nurse-practitioner", title: "Nurse Practitioner", category: "Healthcare", salaryRange: "₹4L - ₹12L", growthOutlook: "High", educationLevel: "Master's in Nursing", skills: ["Patient care", "Diagnosis", "Communication", "Clinical judgment"], relatedMajors: ["Nursing", "Biology", "Public Health"], description: "Provides advanced patient care, diagnoses conditions, and manages treatment plans." },
  { id: "physical-therapist", title: "Physical Therapist", category: "Healthcare", salaryRange: "₹3L - ₹9L", growthOutlook: "High", educationLevel: "Doctor of Physical Therapy", skills: ["Anatomy", "Coaching", "Rehabilitation", "Assessment"], relatedMajors: ["Kinesiology", "Biology", "Health Sciences"], description: "Helps patients recover movement, strength, and quality of life after injuries or illness." },
  { id: "marketing-manager", title: "Marketing Manager", category: "Business", salaryRange: "₹6L - ₹20L", growthOutlook: "Medium", educationLevel: "Bachelor's in Marketing or Business", skills: ["Strategy", "Analytics", "Branding", "Campaigns"], relatedMajors: ["Marketing", "Business Administration", "Communications"], description: "Plans campaigns and market strategies that help organizations grow." },
  { id: "financial-analyst", title: "Financial Analyst", category: "Business", salaryRange: "₹6L - ₹18L", growthOutlook: "Medium", educationLevel: "Bachelor's in Finance, Economics, or Accounting", skills: ["Modeling", "Excel", "Risk analysis", "Research"], relatedMajors: ["Finance", "Economics", "Accounting"], description: "Evaluates investments, budgets, and business performance to guide financial choices." },
  { id: "teacher", title: "Teacher", category: "Education", salaryRange: "₹3L - ₹8L", growthOutlook: "Medium", educationLevel: "Bachelor's in Education plus certification", skills: ["Instruction", "Planning", "Mentoring", "Assessment"], relatedMajors: ["Education", "English", "Mathematics"], description: "Guides students through learning, growth, and classroom experiences." },
  { id: "lawyer", title: "Lawyer", category: "Law", salaryRange: "₹8L - ₹30L", growthOutlook: "Medium", educationLevel: "Bachelor's degree plus JD", skills: ["Argumentation", "Research", "Writing", "Negotiation"], relatedMajors: ["Political Science", "Pre-Law", "History"], description: "Advises clients, researches legal issues, and represents cases or agreements." },
  { id: "graphic-designer", title: "Graphic Designer", category: "Arts", salaryRange: "₹4L - ₹12L", growthOutlook: "Low", educationLevel: "Bachelor's in Graphic Design or portfolio equivalent", skills: ["Typography", "Brand systems", "Illustration", "Layout"], relatedMajors: ["Graphic Design", "Visual Arts", "Marketing"], description: "Creates visual assets for brands, products, publications, and campaigns." },
  { id: "civil-engineer", title: "Civil Engineer", category: "STEM", salaryRange: "₹5L - ₹14L", growthOutlook: "Medium", educationLevel: "Bachelor's in Civil Engineering", skills: ["Structures", "Planning", "Safety", "Project management"], relatedMajors: ["Civil Engineering", "Environmental Engineering", "Urban Planning"], description: "Designs and maintains infrastructure such as roads, bridges, buildings, and water systems." },
];

export const collegeSeeds: College[] = [
  { id: "iit-bombay", name: "IIT Bombay", city: "Mumbai", state: "MH", type: "Public", tuition: 220000, acceptanceRate: 1, enrollment: 12000, majors: ["Computer Science", "Mechanical Engineering", "Data Science", "Physics"], description: "A premier engineering and research institution located in Powai, Mumbai, known globally for its academic excellence." },
  { id: "iit-delhi", name: "IIT Delhi", city: "New Delhi", state: "DL", type: "Public", tuition: 225000, acceptanceRate: 1, enrollment: 11000, majors: ["Computer Science", "Mechanical Engineering", "Civil Engineering", "Robotics"], description: "Located in the capital city, a leading public engineering college focused on research, innovation, and industry collaborations." },
  { id: "iit-madras", name: "IIT Madras", city: "Chennai", state: "TN", type: "Public", tuition: 215000, acceptanceRate: 1, enrollment: 10500, majors: ["Computer Science", "Civil Engineering", "Data Science", "Physics"], description: "Consistently ranked as the top engineering institution in India by the NIRF, set in a lush green campus in Chennai." },
  { id: "iim-ahmedabad", name: "IIM Ahmedabad", city: "Ahmedabad", state: "GJ", type: "Public", tuition: 1250000, acceptanceRate: 1, enrollment: 1000, majors: ["Business Administration", "Finance", "Marketing"], description: "The premier management school in India, globally recognized for its rigorous case-study based curriculum." },
  { id: "iim-bangalore", name: "IIM Bangalore", city: "Bangalore", state: "KA", type: "Public", tuition: 1200000, acceptanceRate: 1, enrollment: 1200, majors: ["Business Administration", "Finance", "Economics"], description: "A leading business school located in India's high-tech hub, offering top-tier postgraduate management programs." },
  { id: "bits-pilani", name: "BITS Pilani", city: "Pilani", state: "RJ", type: "Private", tuition: 570000, acceptanceRate: 5, enrollment: 16000, majors: ["Computer Science", "Mechanical Engineering", "Mathematics", "Physics"], description: "A highly selective private university known for its merit-based admissions and strong entrepreneurial culture." },
  { id: "vit-vellore", name: "VIT Vellore", city: "Vellore", state: "TN", type: "Private", tuition: 198000, acceptanceRate: 15, enrollment: 35000, majors: ["Computer Science", "Mechanical Engineering", "Biology"], description: "A prominent private university offering extensive academic paths, modern infrastructure, and strong placement records." },
  { id: "delhi-university", name: "Delhi University", city: "Delhi", state: "DL", type: "Public", tuition: 15000, acceptanceRate: 8, enrollment: 80000, majors: ["Economics", "Mathematics", "Statistics", "English", "History"], description: "A flagship central university offering a diverse range of undergraduate courses in humanities, commerce, and science." },
  { id: "srcc-delhi", name: "SRCC Delhi", city: "Delhi", state: "DL", type: "Public", tuition: 30000, acceptanceRate: 2, enrollment: 3000, majors: ["Finance", "Economics", "Accounting"], description: "Shri Ram College of Commerce is the premier institute for business and economics education in India." },
  { id: "christ-university", name: "Christ University", city: "Bangalore", state: "KA", type: "Private", tuition: 180000, acceptanceRate: 20, enrollment: 25000, majors: ["Business Administration", "Psychology", "Communications", "Visual Arts"], description: "A popular private university known for its holistic development, beautiful green campus, and diverse student crowd." },
  { id: "aiims-delhi", name: "AIIMS Delhi", city: "New Delhi", state: "DL", type: "Public", tuition: 1628, acceptanceRate: 0.1, enrollment: 3000, majors: ["Nursing", "Biology"], description: "The premier medical research university and hospital in India, offering highly subsidized world-class medical education." },
  { id: "cmc-vellore", name: "CMC Vellore", city: "Vellore", state: "TN", type: "Private", tuition: 52000, acceptanceRate: 2, enrollment: 2000, majors: ["Nursing", "Biology", "Health Sciences"], description: "Christian Medical College is a top-ranked private medical school and hospital, renowned for community health work." },
  { id: "manipal-institute", name: "Manipal Institute of Technology", city: "Manipal", state: "KA", type: "Private", tuition: 425000, acceptanceRate: 12, enrollment: 10000, majors: ["Computer Science", "Graphic Design", "Human-Computer Interaction", "Mechanical Engineering"], description: "A leading private engineering college offering a vibrant campus life and extensive research opportunities." },
  { id: "nit-trichy", name: "NIT Trichy", city: "Tiruchirappalli", state: "TN", type: "Public", tuition: 145000, acceptanceRate: 2, enrollment: 6500, majors: ["Computer Science", "Mechanical Engineering", "Civil Engineering"], description: "The top-ranked National Institute of Technology, offering excellent engineering and technical education." },
  { id: "nit-surathkal", name: "NIT Surathkal", city: "Mangalore", state: "KA", type: "Public", tuition: 150000, acceptanceRate: 2, enrollment: 6000, majors: ["Computer Science", "Civil Engineering"], description: "A premier public engineering institute located on a scenic beachside campus in Karnataka." },
  { id: "bits-hyderabad", name: "BITS Hyderabad", city: "Hyderabad", state: "TG", type: "Private", tuition: 570000, acceptanceRate: 6, enrollment: 5000, majors: ["Computer Science", "Mechanical Engineering", "Mathematics"], description: "A prominent campus of BITS Pilani, offering state-of-the-art laboratory and academic infrastructure." },
  { id: "symbiosis-pune", name: "Symbiosis International", city: "Pune", state: "MH", type: "Private", tuition: 350000, acceptanceRate: 15, enrollment: 18000, majors: ["Business Administration", "Communications", "Marketing", "Law"], description: "A leading private university known for its internationalized campus environment, management, and law programs." },
  { id: "ashoka-university", name: "Ashoka University", city: "Sonepat", state: "HR", type: "Private", tuition: 950000, acceptanceRate: 10, enrollment: 2500, majors: ["Economics", "Political Science", "Psychology", "History"], description: "A premier private liberal arts university offering high-quality multidisciplinary higher education." },
  { id: "st-stephens", name: "St. Stephen's College", city: "Delhi", state: "DL", type: "Public", tuition: 40000, acceptanceRate: 3, enrollment: 1500, majors: ["English", "History", "Mathematics", "Economics"], description: "One of the oldest and most prestigious colleges for arts and sciences affiliated with Delhi University." },
  { id: "anna-university", name: "Anna University", city: "Chennai", state: "TN", type: "Public", tuition: 55000, acceptanceRate: 25, enrollment: 12000, majors: ["Civil Engineering", "Mechanical Engineering"], description: "A leading public state university focusing on engineering, technology, and applied sciences." },
  { id: "jadavpur-university", name: "Jadavpur University", city: "Kolkata", state: "WB", type: "Public", tuition: 10000, acceptanceRate: 5, enrollment: 11000, majors: ["Computer Science", "Mechanical Engineering", "Civil Engineering"], description: "A leading public state university in West Bengal, highly rated for its science and engineering branches." },
  { id: "bhu-varanasi", name: "BHU", city: "Varanasi", state: "UP", type: "Public", tuition: 8000, acceptanceRate: 10, enrollment: 30000, majors: ["Education", "History", "Political Science"], description: "Banaras Hindu University is a historically rich central university and one of the largest residential universities in Asia." },
  { id: "rv-college", name: "RV College of Engineering", city: "Bangalore", state: "KA", type: "Private", tuition: 250000, acceptanceRate: 8, enrollment: 5000, majors: ["Computer Science", "Mechanical Engineering", "Civil Engineering"], description: "A top-tier private engineering college in Bangalore, known for its placements and project collaborations." },
];

export async function seedDataIfNeeded() {
  if (!firebaseReady) return;
  const [careerSnap, collegeSnap] = await Promise.all([getDocs(collection(db, "careers")), getDocs(collection(db, "colleges"))]);
  const batch = writeBatch(db);
  if (careerSnap.empty) {
    careerSeeds.forEach((career) => batch.set(doc(db, "careers", career.id), career));
  }
  if (collegeSnap.empty) {
    collegeSeeds.forEach((college) => batch.set(doc(db, "colleges", college.id), college));
  }
  if (careerSnap.empty || collegeSnap.empty) await batch.commit();
}
